<?php

namespace App\DataFixtures;

use App\Entity\Ingredients;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class IngredientsFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $ingredients = array(
            "farine",
            "sucre",
            "beurre",
            "sel",
            "lait",
            "oeufs",
            "levure",
            "chocolat",
            "vanille",
            "huile",
            "citron",
            "cannelle",
            "eau",
            "crème",
            "amandes",
            "poudre à pâte",
            "cacao",
            "noix de coco",
            "gingembre",
            "noisettes",
            "pistaches",
            "noix",
            "sucre glace",
            "levure chimique",
            "miel",
            "bicarbonate de soude",
            "fécule de maïs",
            "sirop d'érable",
            "cassonade",
            "farine de blé entier",
            "raisins secs",
            "pignons de pin",
            "câpres",
            "tomates séchées",
            "basilic",
            "olives",
            "ail",
            "jus de citron",
            "vinaigre balsamique",
            "parmesan",
            "mozarella",
            "jambon",
            "saucisse",
            "bacon",
            "poulet",
            "boeuf",
            "porc",
            "poisson",
            "crevettes",
            "moules",
            "homard",
            "huîtres",
            "coquilles Saint-Jacques",
            "haricots",
            "pois chiches",
            "lentilles",
            "petits pois",
            "chou",
            "carottes",
            "pommes de terre",
            "courgettes",
            "aubergines",
            "poivrons",
            "oignons",
            "ail",
            "céleri",
            "épinards",
            "salade",
            "champignons",
            "tomates",
            "concombre",
            "brocoli",
            "chou-fleur",
            "poireaux",
            "betteraves",
            "radis",
            "navets",
            "panais",
            "citrouille",
            "patate douce",
            "châtaignes",
            "noix de pécan",
            "noix de macadamia",
            "noix du Brésil",
            "noix de cajou",
            "noix de Grenoble",
            "noix de pin",
            "noix de pecan",
            "noix de macadamia",
            "noix du Brésil",
            "noix de cajou",
            "noix de Grenoble",
            "noix de pin",
            "kiwi",
            "fraise",
            "banane",
            "orange",
            "pomme",
            "poire",
            "raisin",
            "ananas",
            "mangue",
            "pêche",
            "nectarine",
            "abricot",
            "cerise",
            "myrtille",
            "framboise",
            "cassis",
            "groseille",
            "melon",
            "pastèque",
            "citron vert",
            "citron jaune",
            "grenade",
            "canneberge",
            "figue",
            "papaye",
            "rhubarbe",
            "pesto",
            "pâtes",
            "quinoa",
            "pesto",
            "pesto rosso");
            
        foreach ($ingredients as $ingredientName) {
            $ingredient = new Ingredients();
            $ingredient->setNom($ingredientName);
            $manager->persist($ingredient);
        }
        
        $manager->flush();
   
}
}
